openapi: '3.0.0'
info:
  description: "Written for the Cloud Computing 2020W lecture."
  version: "1.0.0"
  title: "Alert REST API Specification"
servers:
- url: http://localhost:3500/
tags:
- name: "alert"
  description: "Alert Service API"
paths:
  /alerts:
    get:
      tags:
      - "alert"
      summary: "List of alerts in a given time frame."
      description: "Returns a JSON with a list of alerts in a given time frame. The list can be filtered by time, event type (exit/entry), and aggergated (count)."
      parameters:
        - in: query
          name: from
          schema:
            type: "string"
            format: "date-time"
          description: Beginning of the time frame
          required: true
        - in: query
          name: to
          schema:
            type: "string"
            format: "date-time"
          description: End of the time frame
          required: true
        - in: query
          name: aggregate
          schema:
            enum:
            - "count"
          description: Count the returned items 
        - in: query
          name: event
          schema:
            type: "string"
            enum:
            - "entry"
            - "exit"
          description: Filter by event type
      responses:
        '200':
          description: "SUCCESS"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/alert-array'
        '4XX':
          description: "ERROR"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"    
    post:
      tags:
      - "alert"
      summary: "Creates a new alert"
      description: "Creates a new alert - a new entry in the list of recognized persons in a particular image."
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/annotated-frame'
          image/jpeg:
              schema:
                type: string
                format: binary
      responses:
        '200':
          description: "SUCCESS"
        '4XX':
          description: "ERROR"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"     
  /alerts/{uuid}:
    get:
      tags:
      - "alert"
      summary: "Returns the Alert with the specified uuid."
      parameters:
        - in: path
          name: uuid
          schema:
            type: "string"
            format: "uuid"
          description: uuid
          required: true
      responses:
        '200':
          description: "SUCCESS"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/alert'
        '4XX':
          description: "ERROR"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"    
    delete:
      tags:
      - "alert"
      summary: "Remove the Alert with the specified uuid."
      parameters:
        - in: path
          name: uuid
          schema:
            type: "string"
            format: "uuid"
          description: uuid
          required: true
      responses:
        '200':
          description: "SUCCESS"
        '4XX':
          description: "ERROR"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse" 
  /probe:
    get:
      tags:
      - "alert"
      summary: "Returns 200 if service is up."
      description: ""
      responses:
        '200':
          description: "SUCCESS"
        '4XX':
          description: "ERROR"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"   
components:
  schemas:
    alert:
      type: "object"
      properties:
        uuid:
          type: "string"
          format: "uuid"
        timestamp:
          type: "string"
          format: date-time
        event:
          type: "string"
          enum:
          - "entry"
          - "exit"
        section:
          type: "integer"
          format: "int32"
        known-persons:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
        extra-info:
          type: "string"
    alert-array:
      type: "object"
      properties:
        alerts:
          type: "array"
          items:
            $ref: '#/components/schemas/alert'
    annotated-frame:
      type: "object"
      required: 
      - image
      properties:
        alert:
          type: "integer"
          format: "int64"
        timestamp:
          type: "string"
          format: date-time
        event:
          type: "string"
          enum:
          - "entry"
          - "exit"
        destination:
          type: "string"
        known-persons:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
        image:
          type: "string"
          format: "byte"
        extra-info:
          type: "string"
    ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "string"